create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  invoice_reference text generated always as ('YT-' || lpad(id::text, 6, '0')) stored,
  full_name text not null,
  email text not null,
  phone_number text not null,
  delivery_area text not null,
  block text not null,
  street text not null,
  building_number text not null,
  floor_apartment text,
  delivery_notes text,
  design_preference text not null default 'Default YourTeck design',
  notes text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint orders_invoice_reference_unique unique (invoice_reference),
  constraint orders_email_format check (email ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'),
  constraint orders_status_check check (status in ('pending', 'underprocess', 'delivered'))
);

create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_status_idx on public.orders (status);
